# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd02042658f131ee00657c42813c7a9bf03de92bfd7f26e9d24dca0f86631e2b777ec23ee1e1aff1a16b136ef14ee2eee831880dc4e7432b1b26748dbdafc91

test:
  secret_key_base: c249366aa05c0c3d97f44557746a9e69e27696922dc9406d1c899ac2a62d5f02ff33e4484f5f52e090518801d680c85661c8ff4404c5a10642519479e1f6bb83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
